-- define some common variable

-- INFO消息命令相关
INFO_CMD = {CREATE = {}, SEND = {}, ADD = {}, DEL ={}, NOTICE = {}, MUTE = {}, AUTH = {}}

INFO_CMD.CREATE.CONF		= 241
INFO_CMD.CREATE.SUCCESS		= 216
INFO_CMD.CREATE.FAILED		= 214

INFO_CMD.SEND.CONF_ATTR		= 292
INFO_CMD.SEND.CLI_INFO		= 285
INFO_CMD.SEND.CONF_INFO		= 290

INFO_CMD.ADD.MEMB			= 200
INFO_CMD.ADD.RINGING		= 220
INFO_CMD.ADD.SUCCESS		= 221
INFO_CMD.ADD.FAILED			= 222

INFO_CMD.DEL.MEMB			= 201
INFO_CMD.DEL.CONF			= 240

INFO_CMD.NOTICE.MEMB_LEAVE	= 223
INFO_CMD.NOTICE.CONF_OVER	= 242

INFO_CMD.MUTE.SURE			= 232
INFO_CMD.MUTE.CANCEL		= 231
INFO_CMD.MUTE.ALL_SURE		= 235
INFO_CMD.MUTE.ALL_CANCLE	= 236

INFO_CMD.AUTH.REQUEST		= 600
INFO_CMD.AUTH.RESPONSE		= 601


-- 与会成员相关
MEMB_ATTR = {STATE = {}, RIGHT = {}, ROLE = {}}

MEMB_ATTR.STATE.IN_CONF		= 5
MEMB_ATTR.STATE.OUT_CONF	= 6

MEMB_ATTR.RIGHT.AUDIO_YES	= 0
MEMB_ATTR.RIGHT.AUDIO_NO	= 1

MEMB_ATTR.ROLE.CHAIRMAN		= 1
MEMB_ATTR.ROLE.COMMON		= 2

-- 会议相关
CONF_ATTR = {TYPE = {}, STATE = {}}

CONF_ATTR.TYPE.AUDIO		= 1
CONF_ATTR.TYPE.DATA			= 3

CONF_ATTR.STATE.ADDING		= 1
CONF_ATTR.STATE.ONGOING		= 2
CONF_ATTR.STATE.OVER		= 3
CONF_ATTR.STATE.NOTSTART	= 4
CONF_ATTR.STATE.NONE		= 5

-- 会议事件相关
CONF_EVENT = {}
CONF_EVENT.CREATE	= "conference-create"
CONF_EVENT.DESTROY	= "conference-destroy"
CONF_EVENT.ADD		= "add-member"
CONF_EVENT.DEL		= "del-member"
CONF_EVENT.MUTE		= "mute-member"
CONF_EVENT.UNMUTE	= "unmute-member"

-- 入会鉴权结果
AUTH_RESULT = {}
AUTH_RESULT.SUCCESS		= 0
AUTH_RESULT.DB_BAD		= 1
AUTH_RESULT.CONF_NONE	= 2
AUTH_RESULT.CODE_ERR	= 3
